project_id = "icoxkprlazegyzgxeeok"

[functions.meli-auth]
verify_jwt = false

[functions.meli-callback]
verify_jwt = false

[functions.meli-webhook]
verify_jwt = false

[functions.scan-bind]
verify_jwt = false

[functions.refresh-shipment]
verify_jwt = false
